package rexready;

public enum Good {
	INFLIGHT_1, INFLIGHT_2, INFLIGHT_3, INFLIGHT_4,
	OUTFLIGHT_2, OUTFLIGHT_3, OUTFLIGHT_4, OUTFLIGHT_5,
	CHEAP_HOTEL_1, CHEAP_HOTEL_2, CHEAP_HOTEL_3, CHEAP_HOTEL_4,
	GOOD_HOTEL_1, GOOD_HOTEL_2, GOOD_HOTEL_3, GOOD_HOTEL_4,
	ALLIGATOR_1, ALLIGATOR_2, ALLIGATOR_3, ALLIGATOR_4,
	AMUSEMENT_1, AMUSEMENT_2, AMUSEMENT_3, AMUSEMENT_4,
	MUSEUM_1, MUSEUM_2, MUSEUM_3, MUSEUM_4
}
